### ISSUE TITLE
Disconnecting after clicking "Turn LED On"

### ISSUE THREAD

**Issue by brandon227** [ricardoromo/BLEArduino#1]
I am connecting to Adafruit 32u4 Feather using an iPhone 7 on iOS 10. After connecting successfully, clicking "Turn LED On" results in the Adafruit disconnecting. The LED does not turn on. The iPhone application remains on the same page until I click "Disconnect Device". What am I doing wrong??

Thank you so much!

**Comment by ricardoromo** [comment]
Hello, I think should be working. but let me take a look on that.
Thanks.

**Comment by brandon227** [comment]
Hello,

I actually was able to get it working. In BluetoothManager.cs under WriteToBLE(), I had to change the first line to

	var services = await BLEDevice.GetServicesAsync(Guid.Parse(*UUID of my device here*))

and a few lines later

	var characteristics = await services[0].GetCharacteristicsAsync(Guid.Parse(*UUID of device here*))
	
Thanks!
Brandon
