### ISSUE TITLE
Missing BLEArduino\Propoerties\AssemblyInfo.cs file

### ISSUE THREAD

**Issue by mikeatmarvel** [ricardoromo/BLEArduino#2]
Very interested to learn form this project.  However, after cloning the project and trying to run on Xamarin.Forms 4.x, I get a File not Found error: /Users/..../BLEArduino/BLEArduino/CSC: Error CS2001: Source file '/Users/..../BLEArduino/BLEArduino/Properties/AssemblyInfo.cs' could not be found. (CS2001) (BLEArduino)

Can you push this file up please?

**Comment by ricardoromo** [comment]
I need to update the sample to  support the latest version of Xamarin Forms, let me update it and push the changes.
